#!/bin/bash

docker compose -p general --env-file ./.env \
-f ./caddy/docker-compose.yml \
-f ./media/docker-compose.yml \
-f ./monitoring/docker-compose.yml \
-f ./postgres/docker-compose.yml \
-f ./discordbot/docker-compose.yml \
"$@"

# -f ./matrix/docker-compose.yml \
# -f ./traefik/docker-compose.yml \
# -f ./hasura/docker-compose.yml \
# -f ./website/docker-compose.yml \
#-f ./minecraft/docker-compose.yml \
