version: "3.8"

services:
  vpn:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - $CONTAINERS_PATH/media/config/vpn:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    ports:
      - "8112:8112"

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    # network_mode: host # port 8112
    # expose: [8112]
    network_mode: service:vpn # run on the vpn network
    # ports:
    # - "8112:8112"
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/Amsterdam # timezone, defined in .env
    volumes:
      - $CONTAINERS_PATH/media/downloads:/downloads # downloads folder
      - $CONTAINERS_PATH/media/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    # network_mode: host # port 9117
    expose: [9117]
    ports:
      - "9117:9117"
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/Amsterdam # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONTAINERS_PATH/media/downloads/blackhole:/downloads # place where to put .torrent files for manual download
      - $CONTAINERS_PATH/media/config/jackett:/config # config files

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=media.stingalleman.dev #optional
    volumes:
      - $CONTAINERS_PATH/media/config/jellyfin:/config
      - $CONTAINERS_PATH/media/library:/data
      - /opt/vc/lib:/opt/vc/lib #optional
    expose: [8096]
    ports:
      # - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      # - /dev/vcsm:/dev/vcsm #optional
      # - /dev/vchiq:/dev/vchiq #optional
      # - /dev/video10:/dev/video10 #optional
      # - /dev/video11:/dev/video11 #optional
      # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    # network_mode: host # port 8989
    # ports:
    #   - "8990:8989"
    expose: [8989]
    ports:
      - "8989:8989"
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/Amsterdam # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONTAINERS_PATH/media/config/sonarr:/config # config files
      - $CONTAINERS_PATH/media/library/tv:/tv # tv shows folder
      - $CONTAINERS_PATH/media/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/Amsterdam # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONTAINERS_PATH/media/config/radarr:/config # config files
      - $CONTAINERS_PATH/media/library/movies:/movies # movies folder
      - $CONTAINERS_PATH/media/downloads:/downloads # download folder
    expose: [7878]
    ports:
      - "7878:7878"

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/Amsterdam # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - $CONTAINERS_PATH/media/config/bazarr:/config # config files
      - $CONTAINERS_PATH/media/library/movies:/movies # movies folder
      - $CONTAINERS_PATH/media/library/tv:/tv # tv shows folder
    expose: [6767]
