version: "3.8"

# ./compose kill -s HUP squid # restart squid config

services:
  squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid
      - $CONTAINERS_PATH/squid/squid.conf:/etc/squid/squid.conf
      - $CONTAINERS_PATH/squid/.users:/etc/squid/.users
    restart: always
