global:
  scrape_interval: 15s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "blackbox"
    metrics_path: /probe
    scrape_interval: 5m
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - https://stingalleman.nl
          - https://core.pakket.sh
          - https://pakket.sh
          - https://cdn.stingalleman.nl
          - https://pve.boem
          - https://ca.boem
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 # The blackbox exporter's real hostname:port.

  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [gemairo.local.boem:9100]
        labels:
          instance: "gemairo"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

      - targets: [10.10.10.2:9100]
        labels:
          instance: "chernobyl"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

      - targets: [10.10.10.2:9100]
        labels:
          instance: "reactor"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

      - targets: [10.10.10.10:9100]
        labels:
          instance: "internals"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

  - job_name: caddy
    static_configs:
      - targets: ["caddy:1990"]
        labels:
          instance: "gemairo"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

      - targets: ["10.10.10.10:1990"]
        labels:
          instance: "internals"
          city: "Amsterdam"
          latitude: 52.33626806224156
          longitude: 4.886583946358772

  - job_name: adguard
    static_configs:
      - targets: ["10.10.10.10:9617"]

  - job_name: "pve"
    static_configs:
      - targets:
          - 10.10.10.2:8008 # Proxmox VE node with PVE exporter.
    metrics_path: /pve
    params:
      module: [default]
