version: "3.8"

services:
  discordbot:
    build: $CONTAINERS_PATH/discordbot/src
    image: discordbot:latest
    restart: unless-stopped
    env_file: ../.env
    environment:
      - DB_PATH=/db.sqlite
    volumes:
      - $CONTAINERS_PATH/discordbot/db.sqlite:/db.sqlite3
