version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8991:5432"
      - "5432:5432"
    volumes:
      - ${CONTAINERS_PATH}/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
