#!/bin/bash

psql -U "$POSTGRES_USER" << EOF

EOF

# CREATE DATABASE "x";
# CREATE USER "xx_user" WITH ENCRYPTED PASSWORD '$POSTGRES_xx_PASSWORD';
# GRANT ALL PRIVILEGES ON DATABASE "xx" TO "xx_user";